---
env:
  - GO111MODULE=on
  - CGO_ENABLED=0
before:
  hooks:
    - go mod download

builds:
  - id: package-validator-linux
    main: ./cmd/package-validator/package-validator.go
    binary: package-validator
    ldflags:
      - -X github.com/garethjevans/package-validator/pkg/version.Version={{.Version}} -X github.com/garethjevans/package-validator/pkg/version.Revision={{.ShortCommit}} -X github.com/garethjevans/package-validator/pkg/version.BuildDate={{.CommitDate}} -X github.com/garethjevans/package-validator/pkg/version.BuiltBy=goreleaser
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - s390x
      - ppc64le

  - id: package-validator-darwin
    main: ./cmd/package-validator/package-validator.go
    binary: package-validator
    ldflags:
      - -X github.com/garethjevans/package-validator/pkg/version.Version={{.Version}} -X github.com/garethjevans/package-validator/pkg/version.Revision={{.ShortCommit}} -X github.com/garethjevans/package-validator/pkg/version.BuildDate={{.CommitDate}} -X github.com/garethjevans/package-validator/pkg/version.BuiltBy=goreleaser
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

  - id: package-validator-windows-amd64
    main: ./cmd/package-validator/package-validator.go
    binary: package-validator
    ldflags:
      - -X github.com/garethjevans/package-validator/pkg/version.Version={{.Version}} -X github.com/garethjevans/package-validator/pkg/version.Revision={{.ShortCommit}} -X github.com/garethjevans/package-validator/pkg/version.BuildDate={{.CommitDate}} -X github.com/garethjevans/package-validator/pkg/version.BuiltBy=goreleaser
    goos:
      - windows
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
  algorithm: sha256

changelog:
  skip: false

release:
  draft: false
  prerelease: false
  name_template: "{{.Tag}}"

brews:
  - name: package-validator
    tap:
      owner: garethjevans
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: garethjevans
      email: gareth@bryncynfelin.co.uk
    folder: Formula
    description: "Utility to validate a component structure"
